// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using PhotoSharing.Api.Data;

#nullable disable

namespace PhotoSharing.Api.Migrations
{
    [DbContext(typeof(PhotoSharingDbContext))]
    [Migration("20260216201939_ReplaceIsLowQualityWithVisibility")]
    partial class ReplaceIsLowQualityWithVisibility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhotoSharing.Api.Entities.EditHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("changed_by");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_key");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("field_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<string>("PhotoId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("photo_id")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_edit_history_time");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("idx_edit_history_user");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("idx_edit_history_photo");

                    b.ToTable("edit_history");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.ExifMetadata", b =>
                {
                    b.Property<string>("PhotoId")
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("photo_id")
                        .IsFixedLength();

                    b.Property<string>("Aperture")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("aperture");

                    b.Property<string>("CameraMake")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("camera_make");

                    b.Property<string>("CameraModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("camera_model");

                    b.Property<string>("FocalLength")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("focal_length");

                    b.Property<int?>("Iso")
                        .HasColumnType("integer")
                        .HasColumnName("iso");

                    b.Property<string>("Lens")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lens");

                    b.Property<string>("RawExif")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_exif");

                    b.Property<string>("ShutterSpeed")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("shutter_speed");

                    b.Property<DateTime?>("TakenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at");

                    b.HasKey("PhotoId");

                    b.ToTable("exif_metadata");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.Face", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BboxHeight")
                        .HasColumnType("integer")
                        .HasColumnName("bbox_height");

                    b.Property<int>("BboxWidth")
                        .HasColumnType("integer")
                        .HasColumnName("bbox_width");

                    b.Property<int>("BboxX")
                        .HasColumnType("integer")
                        .HasColumnName("bbox_x");

                    b.Property<int>("BboxY")
                        .HasColumnType("integer")
                        .HasColumnName("bbox_y");

                    b.Property<string>("ClusterId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cluster_id");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(512)")
                        .HasColumnName("embedding");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("PhotoId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("photo_id")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .HasDatabaseName("idx_faces_cluster");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("idx_faces_person");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("idx_faces_photo");

                    b.ToTable("faces");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.ImageEmbedding", b =>
                {
                    b.Property<string>("PhotoId")
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("photo_id")
                        .IsFixedLength();

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.HasKey("PhotoId");

                    b.ToTable("image_embeddings");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("persons");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.Photo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateNotEarlierThan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_not_earlier_than");

                    b.Property<DateTime?>("DateNotLaterThan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_not_later_than");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_filename");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibility");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("idx_photos_place");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("idx_photos_visibility");

                    b.HasIndex("DateNotEarlierThan", "DateNotLaterThan")
                        .HasDatabaseName("idx_photos_date_range");

                    b.ToTable("photos");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameSv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_sv");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("NameEn")
                        .HasDatabaseName("idx_places_name_en");

                    b.HasIndex("NameSv")
                        .HasDatabaseName("idx_places_name_sv");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("idx_places_parent");

                    b.HasIndex("NameSv", "ParentId")
                        .IsUnique()
                        .HasDatabaseName("idx_places_name_parent_unique");

                    b.ToTable("places");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.User", b =>
                {
                    b.Property<string>("FirebaseUid")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("firebase_uid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.HasKey("FirebaseUid");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.EditHistory", b =>
                {
                    b.HasOne("PhotoSharing.Api.Entities.Photo", "Photo")
                        .WithMany("EditHistory")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.ExifMetadata", b =>
                {
                    b.HasOne("PhotoSharing.Api.Entities.Photo", "Photo")
                        .WithOne("ExifMetadata")
                        .HasForeignKey("PhotoSharing.Api.Entities.ExifMetadata", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.Face", b =>
                {
                    b.HasOne("PhotoSharing.Api.Entities.Person", "Person")
                        .WithMany("Faces")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PhotoSharing.Api.Entities.Photo", "Photo")
                        .WithMany("Faces")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.ImageEmbedding", b =>
                {
                    b.HasOne("PhotoSharing.Api.Entities.Photo", "Photo")
                        .WithOne("ImageEmbedding")
                        .HasForeignKey("PhotoSharing.Api.Entities.ImageEmbedding", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.Photo", b =>
                {
                    b.HasOne("PhotoSharing.Api.Entities.Place", "Place")
                        .WithMany("Photos")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Place");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.Place", b =>
                {
                    b.HasOne("PhotoSharing.Api.Entities.Place", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.Person", b =>
                {
                    b.Navigation("Faces");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.Photo", b =>
                {
                    b.Navigation("EditHistory");

                    b.Navigation("ExifMetadata");

                    b.Navigation("Faces");

                    b.Navigation("ImageEmbedding");
                });

            modelBuilder.Entity("PhotoSharing.Api.Entities.Place", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
